chyh1990/yaml-rust

- src/scanner.rs
Hello
I noticed the ScanError struct did not implement the Error trait, so I've implemented it.
> Implementation of std::scanner::Error for ScanError

- README.md
This shows what versions you currently released on crates.io and under which license.
> added crates.io shields to readme

- Cargo.toml
- src/lib.rs
- src/yaml.rs
This allows the original order of keys in a YAML file to be preserved. The feature is off by default.
> Add preserve_order feature to use LinkedHashMap instead of BTreeMap

- src/scanner.rs
- src/yaml.rs
Hey, after #23 I played a bit around with malformed input.
`----` actually caused an infinite loop leaking memory.
Here is a fix to that.
cheers
> Fix logic error that caused infinite loop

- Cargo.toml
The newer versions provide an IntoIterator implementation which I need. This is not a breaking change because yaml-rust will continue to work with the old versions of linked-hash-map.
> Allow range of linked-hash-map versions

- src/yaml.rs
> add `into_` counterparts for all `as_` methods

- src/emitter.rs
Hey, I was playing around with the `YamlEmitter` and noticed that it did not yet support complex hashmap key and instead returned an `Error`. With this PR I'm trying to introduce this functionality, please give it a try.
Thank you very much
> fixed: emitter also emits complex keys

- src/emitter.rs
This fixes the issue #26.
Also, I wonder if it is possible to use `str::contains` with an array of `char`.
> Added an option to avoid emitting quotes.

- src/parser.rs
- src/yaml.rs
When preparing the PR for the second part of #40, I suddenly remembered when I hadn’t used the approach to add an extra trait method for `EventReceiver`: If you do use the markers, you have to supply an implementation for `on_event()` even though it will never be used.
Here is an approach that seems better: A new trait `MarkedEventReceiver` whose `on_event()` accepts a marker and is implemented for all `EventReceiver`s.
Apologies for the mess created by my forgetfulness.
> Introduce a new trait for event receivers that want markers.

- .travis.yml
- appveyor.yml
So recent changes to crates.io have broken the Travis build. See https://users.rust-lang.org/t/crates-io-compatibility-with-old-cargo/9127 for more information, but basically nothing will work with Cargo <0.9 (which corresponds to Rust 1.8). I've therefore removed Rust 1.0/1.1/1.5 from the build matrix. I've added in 1.8 as the first usable version, and 1.16 as the most recent stable, as well as the current beta. 
I've also marked nightly as "allowed to fail", because it does at various points (like today) but this shouldn't break yaml-rust. For that reason, I've switched over AppVeyor to using 1.16 which seems to work fine and won't break randomly like nightly.
> Upgrade Rust versions in Travis/AppVeyor to working ones

- src/emitter.rs
- src/yaml.rs
Ran into a couple of small unused warnings while compiling
> Remove warnings about unused items

- src/emitter.rs
To understand why we want to do this, please refer to this issue on ktmpl repository (a way to have templates for kubernetes):
https://github.com/InQuicker/ktmpl/issues/15
The problem applies only to string used as keys, but given that the emitters right now doesn't differentiate the two cases for string, I think is better to do it also for values instead of introducing branching and/or flag variables (can't think of cleaner solution for now).
> Quotes string starting with a dot

- README.md
Adds the missing syntax mode for TOML, and fixes the Rust syntax highlighting syntax
> Add/fix README syntax highlighting

- src/parser.rs
- src/yaml.rs
- tests/spec_test.rs
Also: Optimize built-in Yaml deserializer to avoid one scalar value cloning step.
Not sure about the names, maybe somebody has a better idea?
Closes chyh1990/yaml-rust#74
> Allow clients to get ownership of events

- Cargo.toml
- src/emitter.rs
- tests/spec_test.rs
Cherry-picked from https://github.com/palfrey/yaml-rust/pull/1:
Currently, heavily nested arrays or hashes used as keys of hashes (such as a hash<hash<array<_>, _>, _>) were either illegally written, or caused an error when attempted to be emitted. This fixes that situation by using the ? ... : YAML mapping form (as shown in example 2.11 [here](http://yaml.org/spec/1.2/spec.html#id2760395)), which is more amenable to writing complex keys.
If the key of a hashmap is not complex (i.e. a number, string, etc), then the emitting code is unchanged.
> Arbitrarily-nested hashes/arrays emitted as hash keys

- src/parser.rs
This eliminates calls to clone() and to_owned() in the parser
- Peeking now returns reference only
- To obtain value, fetch_token needs to be called
- The parser was adapted accordingly
- Also: Pass anchor name by value to register_anchor
> Parser: Do not clone on peeking

- index.html
Since it is published as a crate, I guess it makes more sense to use it from there.
> index.html: Use yaml-rust from crates.io

- src/scanner.rs
This is necessary to have MarkedEventReceiver make any sense at all …
> Allow access to Marker’s content.

- src/parser.rs
The current parser is a push parser that encapsulates a pull parser. It performs a self-validation on the underlying state-machine model - panicking in case the latter is producing a sequence of events that is not valid.
This pull request makes the pull parser accessible for the clients, providing a next() and a peek() method. Pull parsers are more user-friendly than push parsers in general...
Note that it also renames peek() to peek_token(), as it provides a peek() method to the clients.
The push parser stays, performing the self-validation, but now using the pull parser interface.
> Make pull parser accessible

- src/scanner.rs
This is a simple change to allow the Marker to be gathered from the ScanError struct
> Allow access to the Marker from ScanError

- src/emitter.rs
This should allow the `EmitError` to be used as a `foreign_link` within an `error_chain`
> Add a cause() method to EmitError

- src/scanner.rs
- src/yaml.rs
YAML 1.2 has special handling of indicators to be compatible with JSON.
The following is equivalent to `{"a": "b"}` (note, no space after `:`):
{"a":b}
But without the quoted key, a space is required. So the `:` here is part
of the plain scalar:
{a:b}  # == {"a:b"}
A plain scalar can also start with a `:` as long as it's followed by
"safe" characters:
{a: :b}  # == {"a": ":b"}
(Fixes #118)
(See #116 for failing build)
> Fix handling of indicators in plain scalars to conform to YAML 1.2

- .travis.yml
- README.md
- appveyor.yml
- src/emitter.rs
- tests/test_round_trip.rs
The emitter omitted quotes for strings that start with `0x` those would
subsequently be parsed as strings again. This should fix #133.
> Fix emitting hexlike strings without quotes

- README.md
- src/emitter.rs
- src/parser.rs
- src/scanner.rs
- src/yaml.rs
Fix spelling in several places - mostly variable names, error string literals and documentation, although one test function was renamed.
> Spellcheck

- Cargo.toml
Older versions of linked-hashmap are unsound so it is better if this repository doesn't depend on those. 
Advisory: https://github.com/RustSec/advisory-db/issues/298
If you need further guidance, you can consult the wg-secure-code on Rust Zulip
> bump linked hashmap to 5.3+
